export const FooterText = {
    th: {
        about: 'สมุนไพรพื้นบ้าน',
        description: 'เว็ปไซต์นี้รวมรวบสมุนไพรพื้นบ้าน ไว้สำหรับการศึกษา เป้าหมายหลักคือการใช้สมุนไพรพื้นบ้านเพื่อรักษาโรค',
        learnMore: 'เรียนรู้เพิ่มเติม',
        search: 'การค้นหา ',
        herbs: 'ค้นหาสมุนไพร',
        symptoms: 'ค้นหาสมุนไพรตามอาการ ',
        service: 'บริการ',
        query: 'สอบถาม',
        articles: 'บทความเกี่ยวกับสมุนไพร',
        aboutUs: 'เกี่ยวกับเรา',
        contact: 'ติดต่อเรา โทร:',
        question: 'คำถามที่พบบ่อย',
        address: 'ที่อยู่',
    },
    en: {
        about: 'Local herbs',
        description: 'This website includes folk herbs. For education The main goal is to use local herbs to treat diseases.',
        learnMore: 'Learn More',
        search: 'Search',
        herbs: 'Find herbs',
        symptoms: 'Find herbs as symptoms ',
        service: 'Service',
        query: 'query',
        articles: 'Herbal articles',
        aboutUs: 'About us',
        contact: 'Contact Us',
        question: 'frequently asked Questions',
        address: 'address',
    }
};
