export { default as Loader } from './Loader';
// export { default as BtnLang } from './Common/Btn/BtnLang';
// export { default as NavbarLang } from './Common/Navbar/NavbarLang';
export { default as CardColum } from './Common/Card/CardColum';
export { default as CardHeader } from './Common/Card/CardHeader';
export { default as CardHerb } from './Common/Card/CardHerb';
export { default as CardDrug } from './Common/Card/CardDrug';
export { default as CardHeaderHerb } from './Common/Card/CardHeaderHerb';
export { default as Navbar } from './Common/Navbar/Navbar';
export { default as FormLogin } from './Common/Form/FormLogin';
export { default as FormSearch } from './Common/Form/FormSearch';
export { default as FormHeaderHerb } from './Common/Form/FormHeaderHerb';
export { default as JumbotronOnlyText } from './Common/Jumbotron/JumbotronOnlyText';
export { default as JumbotronHeader } from './Common/Jumbotron/JumbotronHeader';
export { default as JumbotronTwoSection } from './Common/Jumbotron/JumbotronTwoSection';
export { default as JumbotronWithImage } from './Common/Jumbotron/JumbotronWithImage';
export { default as JumbotronDescriptionCreate } from './Common/Jumbotron/JumbotronDescriptionCreate';
// export { default as FooterTextOnly } from './Common/Footer/FooterTextOnly';
export { default as Pagination } from './Common/Pagination/index';
export { default as Footer } from './Common/Footer/Footer';
